export const LOADING = "LOADING"
export const LOAD_CURRENCY_LIST = "LOAD_CURRENCY_LIST"
export const ERROR_WHILE_FETCHING_INITIAL_CURRENCY_LIST =
  "ERROR_WHILE_FETCHING_INITIAL_CURRENCY_LIST"
export const CITY_TO_SEARCH = "CITY_TO_SEARCH"
export const SNACKBAR_STATUS = "SNACKBAR_STATUS"
export const USER_SELECTED_CURRENCY = "USER_SELECTED_CURRENCY"
