export const LOADING = "LOADING"
export const LOAD_CURRENCY_LIST = "LOAD_CURRENCY_LIST"
export const ERROR_WHILE_FETCHING_INITIAL_CURRENCY_LIST =
  "ERROR_WHILE_FETCHING_INITIAL_CURRENCY_LIST"
export const SNACKBAR_STATUS = "SNACKBAR_STATUS"
export const USER_SELECTED_CURRENCY = "USER_SELECTED_CURRENCY"
export const LOAD_SELECTED_TICKER_DATA = "LOAD_SELECTED_TICKER_DATA"
export const CURRENT_WEBSOCKET_CONNECTION = "CURRENT_WEBSOCKET_CONNECTION"
